#!/bin/bash
#
# Xclients
#

errfile="${HOME}/.xsession-errors"
if ( umask 077 && cp /dev/null "${errfile}" 2> /dev/null ); then
    chmod 600 "${errfile}"
        exec > "${errfile}" 2>&1
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for SCRIPT in /etc/X11/xinit/xinitrc.d/*.sh; do
        if [ -f ${SCRIPT} ]; then
            . ${SCRIPT} > /dev/null 2>&1
        fi
    done
fi

if [ -f /etc/X11/Xresources ]; then
    xrdb -load /etc/X11/Xresources
fi

if [ -f ${HOME}/.Xresources ]; then
    xrdb -merge ${HOME}/.Xresources
fi

# setxkbmap -model pc105 -layout us -option ''

if [ -f /etc/X11/Xmodmap ]; then
    xmodmap /etc/X11/Xmodmap
fi

if [ -f ${HOME}/.Xmodmap ]; then
    xmodmap ${HOME}/.Xmodmap
fi

XSESSION=/usr/bin/icewm-session
exec ${XSESSION}
