#!/bin/bash
#
# Xclients
#

errfile="${HOME}/.xsession-errors"
if ( umask 077 && cp /dev/null "${errfile}" 2> /dev/null ); then
    chmod 600 "${errfile}"
        exec > "${errfile}" 2>&1
fi

if [ -z "$UID" ]; then
    export UID=`id --user`
fi

if [ -z "$XDG_CONFIG_DIRS" ]; then
    export XDG_CONFIG_DIRS="/etc/xdg"
fi

if [ -z "$XDG_DATA_DIRS" ]; then
    export XDG_DATA_DIRS="/usr/share"
fi

if [ -d $XDG_RUNTIME_DIR ]; then
    chmod 700 $XDG_RUNTIME_DIR
else
    mkdir -m 700 $XDG_RUNTIME_DIR
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for SCRIPT in /etc/X11/xinit/xinitrc.d/*.sh; do
        if [ -f ${SCRIPT} ]; then
            . ${SCRIPT} > /dev/null 2>&1
        fi
    done
fi

if [ ! -d $XDG_RUNTIME_DIR/ltsm ]; then
    # init ltsm environment
    mkdir $XDG_RUNTIME_DIR/ltsm
fi

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval $(dbus-launch --sh-syntax --close-stderr --exit-with-x11)
fi

if [ -x /usr/bin/dbus-update-activation-environment ]; then
    dbus-update-activation-environment --systemd --all
fi

if [ -f /etc/ltsm/xsetup ]; then
    . /etc/ltsm/xsetup
fi

# Xorg complete
if [ -f ${HOME}/.Xresources ]; then
    xrdb -merge ${HOME}/.Xresources
fi

if [ -f ${HOME}/.ltsm/.Xresources ]; then
    xrdb -merge ${HOME}/.ltsm/.Xresources
fi

if [ -f ${HOME}/.Xmodmap ]; then
    xmodmap ${HOME}/.Xmodmap
fi

# model:
# setxkbmap -model pc105 -layout us -option ''
#
# change layout:
setxkbmap -option ""
setxkbmap -layout "us,ru" -variant ",winkeys" -option "grp:ctrl_shift_toggle"

#
# change symbol:
# setxkbmap -symbols "+kpdl(dotoss)+kpdl(dotoss):2"

if [ -z "$XSESSION" ]; then
    if [ -x /usr/bin/icewm-session ]; then
        XSESSION=/usr/bin/icewm-session
    else
        XSESSION=/usr/bin/xterm
    fi
fi

DISPLAYNUM=$(echo ${DISPLAY} | cut --bytes=2- -)
env | sort > $XDG_RUNTIME_DIR/ltsm/env_session_${DISPLAYNUM}
echo "$DBUS_SESSION_BUS_ADDRESS" > $XDG_RUNTIME_DIR/ltsm/dbus_session_${DISPLAYNUM}

exec ${XSESSION}
