#!/bin/bash
#
# Xclients
#

errfile="${HOME}/.xsession-errors"
if ( umask 077 && cp /dev/null "${errfile}" 2> /dev/null ); then
    chmod 600 "${errfile}"
        exec > "${errfile}" 2>&1
fi

if [ -d $XDG_RUNTIME_DIR ]; 
    chmod 700 $XDG_RUNTIME_DIR
else
    mkdir -m 700 $XDG_RUNTIME_DIR
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for SCRIPT in /etc/X11/xinit/xinitrc.d/*.sh; do
        if [ -f ${SCRIPT} ]; then
            . ${SCRIPT} > /dev/null 2>&1
        fi
    done
fi

# init ltsm environment
mkdir $XDG_RUNTIME_DIR/ltsm

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval $(dbus-launch --sh-syntax --close-stderr --exit-with-x11)
fi

DISPLAYNUM=$(echo ${DISPLAY} | cut --bytes=2- -)
env | sort > $XDG_RUNTIME_DIR/ltsm/env_session_${DISPLAYNUM}
echo "$DBUS_SESSION_BUS_ADDRESS" > $XDG_RUNTIME_DIR/ltsm/dbus_session_${DISPLAYNUM}

# /bin/systemctl --user import-environment DISPLAY DBUS_SESSION_BUS_ADDRESS

# Xorg complete
if [ -f /etc/X11/Xresources ]; then
    xrdb -load /etc/X11/Xresources
fi

if [ -f /etc/X11/ltsm.xres ]; then
    xrdb -load /etc/X11/ltsm.xres
fi

if [ -f ${HOME}/.Xresources ]; then
    xrdb -merge ${HOME}/.Xresources
fi

# model:
# setxkbmap -model pc105 -layout us -option ''
#
# change layout:
# setxkbmap -option ""
# setxkbmap -layout "us,ru" -variant ",winkeys" -option "grp:ctrl_shift_toggle"
#
# change symbol:
# setxkbmap -symbols "+kpdl(dotoss)+kpdl(dotoss):2"

if [ -f /etc/X11/Xmodmap ]; then
    xmodmap /etc/X11/Xmodmap
fi

if [ -f ${HOME}/.Xmodmap ]; then
    xmodmap ${HOME}/.Xmodmap
fi

if [ -z "$XSESSION" ]; then
    if [ -x /usr/bin/icewm-session ]; then
        XSESSION=/usr/bin/icewm-session
    else
        XSESSION=/usr/bin/xterm
    fi
fi

xsetroot -solid "#4e7db7"

exec ${XSESSION}
