
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__ltsm_fuse_adaptor_h__adaptor__H__
#define __sdbuscpp__ltsm_fuse_adaptor_h__adaptor__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace LTSM {
namespace Session {

class FUSE_adaptor
{
public:
    static constexpr const char* INTERFACE_NAME = "LTSM.Session.FUSE";

protected:
    FUSE_adaptor(sdbus::IObject& object)
        : object_(object)
    {
        object_.registerMethod("getVersion").onInterface(INTERFACE_NAME).withOutputParamNames("version").implementedAs([this](){ return this->getVersion(); });
        object_.registerMethod("serviceShutdown").onInterface(INTERFACE_NAME).implementedAs([this](){ return this->serviceShutdown(); });
        object_.registerMethod("mountPoint").onInterface(INTERFACE_NAME).withInputParamNames("localPoint", "remotePoint", "fuseSocket").withOutputParamNames("res").implementedAs([this](const std::string& localPoint, const std::string& remotePoint, const std::string& fuseSocket){ return this->mountPoint(localPoint, remotePoint, fuseSocket); });
        object_.registerMethod("umountPoint").onInterface(INTERFACE_NAME).withInputParamNames("localPoint").implementedAs([this](const std::string& localPoint){ return this->umountPoint(localPoint); });
    }

    ~FUSE_adaptor() = default;

private:
    virtual int32_t getVersion() = 0;
    virtual void serviceShutdown() = 0;
    virtual bool mountPoint(const std::string& localPoint, const std::string& remotePoint, const std::string& fuseSocket) = 0;
    virtual void umountPoint(const std::string& localPoint) = 0;

private:
    sdbus::IObject& object_;
};

}} // namespaces

#endif
