
/*
 * This file was automatically generated by sdbus-c++-xml2cpp; DO NOT EDIT!
 */

#ifndef __sdbuscpp__ltsm_fuse_proxy_h__proxy__H__
#define __sdbuscpp__ltsm_fuse_proxy_h__proxy__H__

#include <sdbus-c++/sdbus-c++.h>
#include <string>
#include <tuple>

namespace LTSM {
namespace Session {

class FUSE_proxy
{
public:
    static constexpr const char* INTERFACE_NAME = "LTSM.Session.FUSE";

protected:
    FUSE_proxy(sdbus::IProxy& proxy)
        : proxy_(proxy)
    {
    }

    ~FUSE_proxy() = default;

public:
    int32_t getVersion()
    {
        int32_t result;
        proxy_.callMethod("getVersion").onInterface(INTERFACE_NAME).storeResultsTo(result);
        return result;
    }

    void serviceShutdown()
    {
        proxy_.callMethod("serviceShutdown").onInterface(INTERFACE_NAME);
    }

    bool mountPoint(const std::string& localPoint, const std::string& remotePoint, const std::string& fuseSocket)
    {
        bool result;
        proxy_.callMethod("mountPoint").onInterface(INTERFACE_NAME).withArguments(localPoint, remotePoint, fuseSocket).storeResultsTo(result);
        return result;
    }

    void umountPoint(const std::string& localPoint)
    {
        proxy_.callMethod("umountPoint").onInterface(INTERFACE_NAME).withArguments(localPoint);
    }

private:
    sdbus::IProxy& proxy_;
};

}} // namespaces

#endif
