name: clang-tidy-review
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Run clang-tidy
    - uses: ZedThree/clang-tidy-review@v0.19.0
      id: review
      with:
        split_workflow: true
        clang_tidy_checks: ''
        # List of packages to install
        apt_packages: libkrb5-dev,libpam0g-dev,libgnutls28-dev,freerdp2-dev,libxcb1-dev,libxcb-xtest0-dev,libxcb-xfixes0-dev,libxcb-shm0-dev,libxcb-randr0-dev,libxcb-damage0-dev,libxcb-keysyms1-dev,libxcb-xkb-dev,libxkbcommon-x11-dev,libsdl2-image-dev,qtbase5-dev,libsdbus-c++-dev,libldap-dev,libcups2-dev,libfuse3-dev,libsystemd-dev,libopus-dev,libpcsclite-dev,libp11-kit-dev

        # CMake command to run in order to generate compile_commands.json
        build_dir: tidy
        cmake_command: cmake -Btidy -S. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DLTSM_BUILD_SERVER=on -DLTSM_TOKEN_AUTH=on -DLTSM_BUILD_CLIENT=on -DLTSM_WITH_RDP=on -DLTSM_FUSE2SESSION=on -DLTSM_AUDIO2SESSION=on -DLTSM_PCSC2SESSION=on -DLTSM_PKCS11_AUTH=on -DLTSM_BUILD_X11VNC=on -DLTSM_BUILD_VNC2IMAGE=on -DLTSM_CUPS_BACKEND=on

    # Uploads an artefact containing clang_fixes.json
    - uses: ZedThree/clang-tidy-review/upload@v0.19.0
      id: upload-review
