name: SonarCloud Analyzer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sonarcloud:
    name: SonarCloud Analyzer
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository ) }}
    env:
      SONAR_SCANNER_VERSION: 4.5.0.2216
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update packages
      run: |
       sudo apt-get update
       sudo apt-get -y upgrade
    - name: Install dependencies
      run: |
       sudo apt-get -y install wget libexpat1 libpam0g-dev libgnutls28-dev freerdp2-dev libxcb1-dev \
            libxcb-xtest0-dev libxcb-xfixes0-dev libxcb-shm0-dev libxcb-randr0-dev libxcb-damage0-dev libxcb-keysyms1-dev libsdl2-image-dev qtbase5-dev
       wget \
         http://ftp.us.debian.org/debian/pool/main/s/sdbus-cpp/libsdbus-c++-dev_0.8.3-4~bpo10+1_amd64.deb \
         http://ftp.us.debian.org/debian/pool/main/s/sdbus-cpp/libsdbus-c++-bin_0.8.3-4~bpo10+1_amd64.deb \
         http://ftp.us.debian.org/debian/pool/main/s/sdbus-cpp/libsdbus-c++0_0.8.3-4~bpo10+1_amd64.deb
       dpkg -i libsdbus-c++-dev_0.8.3-4~bpo10+1_amd64.deb libsdbus-c++-bin_0.8.3-4~bpo10+1_amd64.deb libsdbus-c++0_0.8.3-4~bpo10+1_amd64.deb
    - name: Initialize SonarCloud
      run: |
        mkdir -p ~/.sonarcloud
        wget -P ~/.sonarcloud https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        wget -P ~/.sonarcloud https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-"$SONAR_SCANNER_VERSION"-linux.zip
        unzip ~/.sonarcloud/build-wrapper-linux-x86.zip -d ~/.sonarcloud
        unzip ~/.sonarcloud/sonar-scanner-cli-"$SONAR_SCANNER_VERSION"-linux.zip -d ~/.sonarcloud
    - name: Prepare SonarCloud cfamily cache
      uses: actions/cache@v2
      with:
        path: ~/.sonar-cfamily-cache
        key: sonarcloud-${{ hashFiles( 'src/**/*.cpp', 'src/**/*.h' ) }}
        restore-keys: |
          sonarcloud-
    - name: Build
      run: |
        ~/.sonarcloud/build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output make -j 2
    - name: Analyze
      run: |
        ~/.sonarcloud/sonar-scanner-"$SONAR_SCANNER_VERSION"-linux/bin/sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output \
                                                                                     -Dsonar.cfamily.cache.enabled=true \
                                                                                     -Dsonar.cfamily.cache.path="$HOME"/.sonar-cfamily-cache \
                                                                                     -Dsonar.host.url=https://sonarcloud.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
